[build]
builder = "DOCKERFILE"

[deploy]
healthcheckPath = "/up"
healthcheckTimeout = 600
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[deploy.envs]
RAILS_ENV = "production"
RAILS_SERVE_STATIC_FILES = "true"
RAILS_LOG_TO_STDOUT = "true"
RAILS_MAX_THREADS = "5" 