services:
  - type: web
    name: oracle-me-app
    runtime: docker
    plan: free
    buildCommand: docker build -t oracle-me-app .
    startCommand: |
      rails db:reset
      rails assets:precompile
      docker run -p $PORT:3000 oracle-me-app
    envVars:
      - key: RAILS_ENV
        value: production
      - key: RAILS_SERVE_STATIC_FILES
        value: true
      - key: RAILS_LOG_TO_STDOUT
        value: true
      - key: DATABASE_URL
        fromDatabase:
          name: oracle-me-app-db
          property: connectionString
      - key: SECRET_KEY_BASE
        generateValue: true

databases:
  - name: oracle-me-app-db
    plan: free
    databaseName: oracle_me_app_production
    user: oracle_me_app 